name: Auto-Compile LaTeX and Release

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    paths:
      - '**/*.tex' # Any LaTeX file change in the repo

jobs:
  build_and_release:
    runs-on: ubuntu-latest # The operating system where the job will run
    timeout-minutes: 10 # Add a timeout to prevent long runs if it hangs

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Set up LaTeX environment
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full # Install full TeX Live to ensure all packages are present
        sudo apt-get install -y texlive-fonts-extra texlive-xetex # Specific for XeLaTeX and fonts if not in full

    - name: Compile LaTeX
      uses: xu-cheng/latex-action@v2 # Action to compile LaTeX documents
      id: compile_latex # Add an ID to reference this step if needed
      with:
        root_file: main.tex # Specifies the main .tex file to compile in your repo
        args: -xelatex -file-line-error -interaction=nonstopmode # More robust XeLaTeX arguments
        # Ensure the output is in the root of the workspace
        # Output is by default in the root of the workspace for latex-action
      # continue-on-error: true # TEMPORARY: Use this to see if the build fails but still allows release. REMOVE AFTER DIAGNOSIS.

    - name: Check for compiled PDF
      run: |
        if [ ! -f main.pdf ]; then
          echo "Error: main.pdf was not created by LaTeX compilation."
          exit 1
        else
          echo "main.pdf successfully created."
        fi

    - name: Create Release and Upload PDF
      id: create_release # Unique ID for this step
      uses: softprops/action-gh-release@v2 # Action to create a GitHub Release
      if: startsWith(github.ref, 'refs/heads/main') # Ensures it only runs on pushes to 'main' branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub's auto-generated token for authentication
      with:
        tag_name: v${{ github.run_number }} # Auto-generates a version tag (e.g., v1, v2, v3...)
        name: Auto-Release ${{ github.run_number }} # Auto-generates the Release Title
        body: | # This is the Release Description (Markdown supported)
          Automated release for ${{ github.event.repository.name }}.
          Version: ${{ github.run_number }}

          This content is unreviewed and actively being developed. Use at your own risk.
        files: |
          main.pdf # The compiled PDF file that will be attached to the release
